### ISSUE TITLE
Error on "gulp serve"

### ISSUE THREAD

**Issue by minerj101** [microsoft/MinecraftCodex#35]
\Desktop\MinecraftCodex-main> gulp serve
[23:38:23] Using gulpfile ~\OneDrive\Desktop\MinecraftCodex-main\gulpfile.js
[23:38:23] Starting 'serve'...
[23:38:23] Starting 'clean_build'...
[23:38:23] Finished 'clean_build' after 25 ms
[23:38:23] Starting 'copy_behavior_packs'...
[23:38:23] Starting 'copy_resource_packs'...
[23:38:23] Finished 'copy_resource_packs' after 11 ms
[23:38:23] Finished 'copy_behavior_packs' after 37 ms
[23:38:23] Starting 'compile_scripts'...
[23:38:25] 'compile_scripts' errored after 1.39 s
[23:38:25] Error: You must provide the URL of lib/mappings.wasm by calling SourceMapConsumer.initialize({ 'lib/mappings.wasm': ... }) before using SourceMapConsumer
    at readWasm (C:\Users\miner\OneDrive\Desktop\MinecraftCodex-main\node_modules\gulp-typescript\node_modules\source-map\lib\read-wasm.js:8:13)
    at wasm (C:\Users\miner\OneDrive\Desktop\MinecraftCodex-main\node_modules\gulp-typescript\node_modules\source-map\lib\wasm.js:25:16)
    at C:\Users\miner\OneDrive\Desktop\MinecraftCodex-main\node_modules\gulp-typescript\node_modules\source-map\lib\source-map-consumer.js:264:14
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[23:38:25] 'serve' errored after 1.46 s

**Comment by stevelatta** [comment]
is this a clean build of the repo code without any changes?

**Comment by minerj101** [comment]
yes

**Comment by stevelatta** [comment]
Can you please confirm you have the LTS version of Node installed? I have also not tried this with code on OneDrive, it could be that the the unique aspects of OD are causing some issues.

**Comment by jennifermarsman** [comment]
@minerj101 

This PR should resolve: https://github.com/microsoft/MinecraftCodex/pull/42
